---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/davidccunliffe/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - 1password
  - 1password-cli
  - asdf
  - awscli
  - autoconf
  - bash-completion
  - cowsay
  - doxygen
  - gettext
  - gifsicle
  - git
  - gh
  - go
  - gpg
  - httpie
  - iterm2
  - iperf
  - libevent
  - timeout
  - tree
  - node
  - nvm
  - ssh-copy-id
  - spectacles
  - sqlite3
  - tcl-tk
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - xz
  - zlib
  - zsh
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - slack
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

asdf_user: "{{ lookup('env', 'USER') }}"
asdf_user_home: "{{ lookup('env', 'HOME') }}"
asdf_homebrew_retries: 3
asdf_plugins:
  - name: "golang"
    repository: ""
    versions:
      - 1.18.10
    global: 1.18.10
  - name: "helm"
    repository: ""
    versions:
      - 3.11.0
    global: 3.11.0
  - name: "kubectl"
    repository: ""
    versions:
      - 1.25.6
    global: 1.25.6
  - name: "minikube"
    repository: ""
    versions:
      - 1.28.0
    global: 1.28.0
  - name: "python"
    repository: ""
    versions:
      - 2.7.18
      - 3.7.16
      - 3.8.16
      - 3.9.16
    global: 3.9.16
  - name: "terraform"
    repository: ""
    versions:
      - 1.7.3
      - 1.9.3
    global: 1.9.3

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
